version = 0.1

[default.deploy.parameters]
stack_name = "ai-invoice-app-dev"
resolve_s3 = true
s3_prefix = "ai-invoice-app-dev"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "Environment=\"dev\" PresignedUrlExpiry=\"300\" MaxFileSizeBytes=\"10485760\""
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
